### PR TITLE
Parallelize bundler

### PR DESCRIPTION
**Pull request by alachaum**

### CODE REVIEW

**Comment by alachaum** [comment]
@ouranos could you please approve? same as https://github.com/maestrano/docker-web-ruby/pull/19

**Comment by alachaum** [comment]
@ouranos ping :)

**Comment by alachaum** [comment]
Cannot be merged until we've switched to 9.1.7.0
See: https://github.com/bundler/bundler/issues/5202

**Comment by alachaum** [comment]
@BrunoChauvet I think this one should be good now.

**Review by BrunoChauvet — APPROVED** [review]

**Pull request merged**
